### ISSUE TITLE
why you reshape the X into 3D shape

### ISSUE THREAD

**Issue by sherlockhoatszx** [Vict0rSch/deep_learning#10]
Hi, the code runs well, thanks.
I got one question that confuse me , why you reshape the X into 3 dimensions : X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1)) ?does these represent:  nb_samples , timestep and features ? 
Many thanks

**Comment by vict0rsch** [comment]
yes, it's because the data is 1d : it's just a scalar value. See also : https://github.com/Vict0rSch/deep_learning/blob/master/recurrent.md
