### ISSUE TITLE
Original Dataset availability

### ISSUE THREAD

**Issue by DerWizzzard** [Vict0rSch/deep_learning#15]
I would love to recreate that example with the same data that has been used.

However, the dataset is no longer available for download for me.
Is there any way to retrieve it, or can you upload it some place where i can download it?

Thanks :)

**Comment by vict0rsch** [comment]
Indeed ICS website is down. You can still find it there : https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip 

I'll update the post thanks for pointing this out!

**Comment by DerWizzzard** [comment]
Thank you very much!!
