### ISSUE TITLE
Syntax error in np.random.seed

### ISSUE THREAD

**Issue by sonamagr** [Vict0rSch/deep_learning#16]
I m getting below error while executing the program. Please help me to solve it
/recurrent_keras_power.py: line 8: syntax error near unexpected token `1234'
./recurrent_keras_power.py: line 8: `np.random.seed(1234)'

**Comment by vict0rsch** [comment]
looks like a copy-paste error... 

`np.random.seed(1234)` not `np.random.seed(1234)'`
