### ISSUE TITLE
Issues in keras installation via anaconda on ubuntu

### ISSUE THREAD

**Issue by sonamagr** [Vict0rSch/deep_learning#17]
Hi Sir,

Can you please help me in solving the below error in keras installation.

I want to install keras via anaconda in ubuntu.

UnsatisfiableError: The following specifications were found to be in conflict:
  - keras -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by vict0rsch** [comment]
I'm afraid I can not, you should ask on the Keras Github repo and especially there :  https://github.com/fchollet/keras#support
